name: Deploy Next.js to terabrain.ai

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm@8.14.1

      - name: Install dependencies
        run: npx pnpm@8.14.1 install

      - name: Build Next.js project
        run: npx pnpm@8.14.1 run build

      - name: Deploy on GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          commit_message: 'Deploy Next.js to terabrain.ai'
